name = input("waht,s your name:")
print("welcome" , name ,"how are you")
yes=input("?")
country = input("where are you from")
good_jab = input()
print("where are you from?")
age = input("how old are you")
print("how old are you")